version: '2'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 2717:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8082:8080

  redis_db:
    image: "redis:alpine"
    ports:
      - "16379:6379"

volumes:
  data: { }
  postgres:

networks:
  default:
    name: mongodb_network
